3 Models creados
FedeOrefici/asesoria-profesional-pf-henry-Backend pull request #5
Opened 2023-06-17 21:31 UTC by MaxyGrosman2010

Los modelos PriceRange, Description y TypeService

2023-06-17 21:39 UTC, FedeOrefici approved these changes

2023-06-17 23:03 UTC, santicarrizo03 approved these changes

2023-06-17 23:09 UTC, garridomartin requested changes
por favor, ponle una "s" al final de cada timestamp.

2023-06-18 01:11 UTC, MaxyGrosman2010 reviewed
Cambios hechos, por favor rechequear asi nos aseguramos que esta todo bien y se pasa

2023-06-19 00:48 UTC, garridomartin approved these changes
:-)

2023-06-19 16:16 UTC, merged